version: "3"   #specify docker-compose version
services: # Define the services/ containers to be run
## Service mongodb #####
  mongodb: ## name of the service Mongo db
    image: mongo  # specify image to build container from official mongo image
    ports:
      - 27017:27017  # specify port forwarding (default)
      - 3000:3000  #specify ports mapping for the server node (back end)
  
        
  ######### nodeserver Service #############    
  express-server: # # name of the second service
    build: NodeJS  # specify the directory of the Dockerfile
    depends_on:  ##dependance with mongo db
      - mongodb
    network_mode: "service:mongodb"  
    environment:
      DATABASE_URL: 'NodeJS/db.js' # specify the environment database
    
  
  ######  client-angular service ################
  angular-app:  ## name of the third service (client)
    # specify the directory of the Dockerfile
    build: AngularApp  # specify the directory of the Dockerfile
    #network_mode: "service:mongodb"
    depends_on: # dependance whith express server
      - express-server
    ports:
      - 4200:5555 # #specify ports mapping, for communicating with the port 4200 of the back end server to send requests made by users accessing the front end client by the port 5555