version: "3"   #specify docker-compose version
services: # Define the services/ containers to be run
## Service mongodb #####
  mongodb: ## name of the first service
    image: mongo  # specify image to build container from official mongo image
    ports:
    #  - 27017:27017  # specify port forwarding
      - 3000:3000
      - 5555:4200

   
  ######### nodeserver Service #############    
  express-server: # # name of the second service
    build: NodeJS  # specify the directory of the Dockerfile
    depends_on:  ##dependance with mongo db
      - mongodb
    network_mode: "service:mongodb"  
    environment:
      DATABASE_URL: 'NodeJS/db.js'  
     


  ######  client-angular service ################
  angular-app:  ## name of the third service (client)
    # specify the directory of the Dockerfile
    build: AngularApp  # specify the directory of the Dockerfile
    network_mode: "service:mongodb"
    depends_on: # dependance whith express server
      - express-server
